# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "431ea1628c2012538dad6aa6701a49bc"
name = "demoapp2"
handle = "demoapp2-21"
application_url = "https://demoapp2-ok0f.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-59632af1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://demoapp2-ok0f.onrender.com/auth/callback",
  "https://demoapp2-ok0f.onrender.com/auth/shopify/callback",
  "https://demoapp2-ok0f.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
